dist: trusty
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - gcc-7-multilib
      - g++-7
      - g++-7-multilib
install:
  - CXX=g++-7 CC=gcc-7
  - mkdir -p $HOME/deps
  - mkdir -p $HOME/deps/vcpkg
  - pushd $HOME/deps/
  - wget https://github.com/TheWillard/ci-toolchains/raw/master/vcpkg-export-x64-linux.7z
  - 7z x vcpkg-export-x64-linux.7z
  - popd

cache:
  directories:
    - "$HOME/deps/vcpkg/installed"

before_script:
  - CXX=g++-7 CC=gcc-7 cmake . -DCMAKE_TOOLCHAIN_FILE=/home/travis/deps/vcpkg-export-x64-linux/scripts/buildsystems/vcpkg.cmake

script:
  - make
  - ./tools/hemtt
  - ./tools/packageTravis.sh

deploy:
  provider: releases
  api_key:
    secure: tvd1uLziBkyh6Qo9KdHRYj8ZJKszkD0VefamKw7BSeH2fVVWgKOJVsq7BAnEGIr6uq3GXaXXFGDpri2xgXGDB85tguvGLpFK5/LcuuvZIBknjGWLr2m8K8dwl7l9ZYV/0ERHyY9oeBwOSzPZQJ0takSz9q6XmzbTstIWj5mh5faYFKgWcbQNm1HLrMkunCbt4c5xcnaoKJD6kXx+AjO4pmPBiXJ74Up/QUTD5ehULuwiwvGRv8JbBV36pOL3FVrrU9OeYYPTScwBJc5eBkdu6Mts0tXBSwk3gPvrw1BxaN9vaGhoynsY99E7ZDO4GM0uXcoooXKkHliF90wW96NQkPZu8M2jHeVlFa/VHEDxg+JyM0LVSXxYk1EntZOOz+2fp78TAa897OoqIUqZBtiuM8YYz0CNX19csVAO0HS0HtcbDy36ZwO6Dd8EzCGYW7XYw0B2jmevDVPcPt6zN5vUcY3chQddFM5Wz5++pF8O5WXUcXvrJiRC8I3wFB21MCe6lQp0NLVntjJ81Ck0juz4NLnDk9AqLYRz2e7qCuSpIiRrOM7OqckgWTAScVT35pTl1VBKVWmSHtLsvNLwTALzExNMdsqCkZ+oRl8Lx+/REr0Wv4buqyZSeh/itTHf7qWyDImtNKe2P1NQZ8uF8DQ0jLHPSHWyWSuq2GXWkIZ+Nh0=
  file: @grad_replay_intercept.zip
  skip_cleanup: true
  on:
    repo: gruppe-adler/grad_replay_intercept
