version: "{build}"

image: 
  - Visual Studio 2017
  - Ubuntu1804

for:
  -
    matrix:
      only:
        - image: Visual Studio 2017
    cache:
      - c:\tools\prebuild\vcpkg-export-x64-windows-static.7z
    
    install:
      - cd %APPVEYOR_BUILD_FOLDER%
      - git submodule update --init --recursive
      - ps: if(![System.IO.Directory]::Exists('c:\tools\prebuild')) { mkdir c:\tools\prebuild }
      - cd c:\tools\prebuild
      - ps: if(![System.IO.File]::Exists('vcpkg-export-x64-windows-static.7z')) { Invoke-WebRequest https://github.com/TheWillard/ci-toolchains/raw/master/vcpkg-export-x64-windows-static.7z -OutFile vcpkg-export-x64-windows-static.7z }
      - 7z x vcpkg-export-x64-windows-static.7z
      - cd %APPVEYOR_BUILD_FOLDER%

    before_build:
      - mkdir build
      - mkdir vcproj64
      - cd vcproj64
      - cmake .. -G "Visual Studio 15 2017 Win64" -DUSE_64BIT_BUILD=ON -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_TOOLCHAIN_FILE=c:/tools/prebuild/vcpkg-export-20190519-024108/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static
      - cd ..

    build_script:
      - msbuild vcproj64\grad_replay_intercept.sln /m 
      - tools\hemtt.exe build

    after_build:
      - ps: .\tools\packageWindows.ps1

    artifacts:
      - path: build\win64
        name: win64
      - path: addons\grad_replay_intercept.pbo
        name: grad_replay_intercept_pbo
  -
    matrix:
      only:
        - image: Ubuntu1804
    cache:
      - $HOME/deps/vcpkg-export-x64-linux.7z

    install:
      - cd $APPVEYOR_BUILD_FOLDER
      - git submodule update --init --recursive
      - mkdir -p $HOME/deps
      - cd $HOME/deps/
      - if [[ ! -f vcpkg-export-x64-linux.7z ]]; then appveyor DownloadFile https://github.com/TheWillard/ci-toolchains/raw/master/vcpkg-export-x64-linux.7z; fi
      - 7z x vcpkg-export-x64-linux.7z > /dev/null
      - cd $APPVEYOR_BUILD_FOLDER

    before_build:
      - CXX=g++-8 CC=gcc-8 cmake . -DCMAKE_TOOLCHAIN_FILE=$HOME/deps/vcpkg-export-x64-linux/scripts/buildsystems/vcpkg.cmake

    build_script:
      - make
      - ./tools/hemtt build

    after_build:
      - ./tools/packageLinux.sh

    artifacts:
      - path: src\grad_replay_intercept_x64.so
        name: linux64
      - path: addons\grad_replay_intercept.pbo
        name: grad_replay_intercept_pbo

  -
    branches:
      only:
        - master
    
    deploy:
      - provider: GitHub
        auth_token:
          secure: MXV97Ngzyn/C/TrCbWG4tdIZcxS/rTfojUq45KbgspSafhcTut3HseMq2002oYkg
        artifact: zip
        draft: false
        prerelease: false
        force_update: true
        skip_tags: false
        on:
          APPVEYOR_REPO_TAG: true

    configuration: Release

  -
    configuration: Debug
