version: "{build}"

image: Visual Studio 2019 Preview

cache: 
  - c:\tools\vcpkg\installed\
      
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - mkdir c:\tools\prebuild
  - cd c:\tools\prebuild
  - ps: Invoke-WebRequest https://github.com/TheWillard/ci-toolchains/raw/master/vcpkg-export-x64-windows-static.7z -OutFile vcpkg-export-x64-windows-static.7z
  - ps: 7z x vcpkg-export-x64-windows-static.7z
  - cd %APPVEYOR_BUILD_FOLDER%
      
before_build:
  - mkdir build
  - mkdir vcproj64
  - cd vcproj64
  - cmake .. -G "Visual Studio 15 2017 Win64" -DUSE_64BIT_BUILD=ON -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_TOOLCHAIN_FILE=c:/tools/prebuild/vcpkg-export-20190519-024108/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static
  - cd ..

build:
  parallel: true
  verbosity: minimal

build_script:
  - msbuild vcproj64\template-plugin.sln /m 
  - tools\hemtt.exe build
  
after_build:
  - ps: .\tools\packageAppveyor.ps1

artifacts:
- path: build\win64
  name: win64
- path: addons\grad_replay_intercept.pbo
  name: grad_replay_intercept_pbo



for:
-
  branches:
    only:
      - master
  
  deploy:
    - provider: GitHub
      auth_token:
        secure: MXV97Ngzyn/C/TrCbWG4tdIZcxS/rTfojUq45KbgspSafhcTut3HseMq2002oYkg
      artifact: zip
      draft: false
      prerelease: false
      force_update: true
      skip_tags: false
      on:
        APPVEYOR_REPO_TAG: true

  configuration: Release
  
-
  configuration: Debug