version: "{build}"

image: 
  - Visual Studio 2017
  - Ubuntu1804

#cache: 
#  - c:\tools\vcpkg\installed\
      
install:
  - sh: cd $APPVEYOR_BUILD_FOLDER
  - ps: cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  # Windows vcpkg export  
  - ps: mkdir c:\tools\prebuild
  - ps: cd c:\tools\prebuild
  - ps: Invoke-WebRequest https://github.com/TheWillard/ci-toolchains/raw/master/vcpkg-export-x64-windows-static.7z -OutFile vcpkg-export-x64-windows-static.7z
  - ps: 7z x vcpkg-export-x64-windows-static.7z
  # Linux vcpkg export
  - sh: mkdir -p $HOME/deps
  - sh: pushd $HOME/deps/
  - sh: wget https://github.com/TheWillard/ci-toolchains/raw/master/vcpkg-export-x64-linux.7z
  - sh: 7z x vcpkg-export-x64-linux.7z > /dev/null
  - sh: cd $APPVEYOR_BUILD_FOLDER
  - ps: cd %APPVEYOR_BUILD_FOLDER%
      
before_build:
  # Windows CMake
  - ps: mkdir build
  - ps: mkdir vcproj64
  - ps: cd vcproj64
  - ps: cmake .. -G "Visual Studio 15 2017 Win64" -DUSE_64BIT_BUILD=ON -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_TOOLCHAIN_FILE=c:/tools/prebuild/vcpkg-export-20190519-024108/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static
  - ps: ..
  # Linux CMake
  - sh: CXX=g++-8 CC=gcc-8 cmake . -DCMAKE_TOOLCHAIN_FILE=$HOME/deps/vcpkg-export-x64-linux/scripts/buildsystems/vcpkg.cmake

build:
  parallel: true
  verbosity: minimal

build_script:
  # Windows Build
  - ps: msbuild vcproj64\grad_replay_intercept.sln /m 
  - ps: tools\hemtt.exe build
  # Linux Build
  - sh: make
  - sh: .\tools\hemtt build
  
after_build:
  - ps: .\tools\packageWindows.ps1
  - sh: .\tools\packageLinux.ps1

artifacts:
  - path: build\win64
    name: win64
  - path: src\grad_replay_intercept_64.so
    name: linux64
  - path: addons\grad_replay_intercept.pbo
    name: grad_replay_intercept_pbo

for:
-
  branches:
    only:
      - master
  
  deploy:
    - provider: GitHub
      auth_token:
        secure: MXV97Ngzyn/C/TrCbWG4tdIZcxS/rTfojUq45KbgspSafhcTut3HseMq2002oYkg
      artifact: zip
      draft: false
      prerelease: false
      force_update: true
      skip_tags: false
      on:
        APPVEYOR_REPO_TAG: true

  configuration: Release
  
-
  configuration: Debug